---
- name: List all the services
  hosts: linux
  gather_facts: no
  remote_user: root
  connection: ssh
  tasks:
   - name: List all the services
     command: systemctl list-unit-files 
     register: services1
   - name: Print the services   
     debug:
      var: services1.stdout_lines
